# Generated by Django 4.2.24 on 2025-09-11 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inmueble',
            name='precio_mensual',
            field=models.DecimalField(decimal_places=0, max_digits=8),
        ),
    ]
