# Generated by Django 4.2.24 on 2025-09-11 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0002_alter_inmueble_precio_mensual'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inmueble',
            name='habitaciones',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
