# Generated by Django 4.2.24 on 2025-09-12 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0004_imageninmueble'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inmueble',
            name='imagen',
        ),
    ]
