# Generated by Django 4.2.24 on 2025-09-12 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0006_inmueble_imagen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inmueble',
            name='imagen',
        ),
    ]
